# 配置文件请严格遵循 yaml 语法格式，yaml 学习地址:
#  https://ansible-tran.readthedocs.io/en/latest/docs/YAMLSyntax.html
#  http://einverne.github.io/post/2015/08/yaml.html

# 是否强制切换微信号
is_forced_switch: False

# 是否开启自动回复
is_auto_relay: True

# 机器人渠道（1: 图灵机器人，2: 一个AI ,3 : 青云客)
bot_channel: 2

#图灵机器人(http://www.tuling123.com/)免费用户每天可用 100 条。
#请在官网注册并申请 apikey ,userID。
turing_conf:
  apiKey: 'f238afdc27c140fa8bf00a9eb3291eeb'


# 一个 Al (http://www.yige.ai/),这个功能挺多的，朋友们自行申请，训练。
#  client_token.客户端访问令牌。note: 已填入的这个是博主自己申请的。朋友们最好自行申请并替换。
yigeai_conf:
  client_token: '55F3440EFBB9C292BDBAA0A02C3E1B15'

# 指定自动回复的好友名单。（填：文件传输助手，可回复自己，测试效果）
# - '好友1'
# - '好友2'
auto_reply_names:
  - '筱婷'
  - '冀曼雯'
  - '大眼睛'
  - '文件传输助手'
  - '绿萝萝萝lililili'
#  - '到处乱走'
  - 'Yzx'


#------------------------ 定时提醒功能--------------------------
alarm_info:
  #True 开启定时提醒，False 关闭
  is_alarm: True
  #定时发送时间
  alarm_timed: '09:02'

girlfriend_infos:
  -
    wechat_name: '到处乱走'
    city_name: '长沙'
    dictum_channel : 3 # 格言渠道（1 : 词霸（每日英语，双语）, 2 : ONE●一个，3:土味情话，4 : 一言，5：笑话)(可空)
    start_date: '2019-06-16'
    sweet_words: '来自Yzx(法兰克)'
  -
    wechat_name: '筱婷'
    city_name: '长沙'
    dictum_channel : 3
    start_date: '2019-06-15'
    sweet_words: '来自Yzx(法兰克)'
  -
    wechat_name: 'Yzx'
    city_name: '长沙'
    dictum_channel : 3
    start_date: '2019-06-15'
    sweet_words: '来自Yzx(法兰克)'
  # -
  #   wechat_name: '龟龟'
  #   city_name: '长沙'
  #   dictum_channel : 3
  #   start_date: '2019-04-28'
  #   sweet_words: '来自Yzx(法兰克)'
  -
    group_name: '技术交流群'
    city_name: '长沙'
    dictum_channel : 4
    start_date: '2018-11-30'
    sweet_words: '来自帅气的群主'

hookup_girls:
  -
    wechat_name: '筱婷'
    city_name: '长沙'
    dictum_channel : 3
    start_date: '2019-06-16'
    sweet_words: '来自Yzx(法兰克)'
  # -
  #   wechat_name: '到处乱走'
  #   city_name: '长沙'
  #   dictum_channel : 3
  #   start_date: '2019-06-16'
  #   sweet_words: '来自Yzx(法兰克)'
  # -
  #   wechat_name: 'Yzx'
  #   city_name: '长沙'
  #   dictum_channel : 1
  #   start_date: '2019-06-14'
  #   sweet_words: '来自Yzx(法兰克)'
  # -
  #   group_name: '技术交流群'
  #   city_name: '长沙'
  #   dictum_channel : 3
  #   start_date: '2019-6-15'
  #   sweet_words: '来自骚气的大哥'


